export const data = [
{
  id: 1,
  name: "Floral black",
  description: "Floral black orange silk dress for women, prom dress, silk kimono, gift for her, wedding party, birthday, cocktail silk dress with sleeves",
  price: 590,
  image: ['/content/image/floralBlack/floralBlack0.png', 
  '/content/image/floralBlack/floralBlack1.png', '/content/image/floralBlack/floralBlack2.png', 
  '/content/image/floralBlack/floralBlack3.png', '/content/image/floralBlack/floralBlack4.png',
  '/content/image/floralBlack/floralBlack5.png', '/content/image/floralBlack/floralBlack6.png',
  '/content/image/floralBlack/floralBlack7.png', '/content/image/floralBlack/floralBlack8.png',
  '/content/image/floralBlack/floralBlack9.png'],
  showMore:false,
  category: "floral"
},
{
  id: 2,
  name: "Sakura",
  description: "Prom Green pink silk dress with sleeves for women, Sakura kimono dress,gift for her,teal dress, wedding,cocktail bridesmaid robe birthday",
  price: 690,
  image: ['/content/image/floralSakura/floralSakura0.png', 
  '/content/image/floralSakura/floralSakura1.png', '/content/image/floralSakura/floralSakura2.png', 
  '/content/image/floralSakura/floralSakura3.png', '/content/image/floralSakura/floralSakura4.png',
  '/content/image/floralSakura/floralSakura5.png', '/content/image/floralSakura/floralSakura6.png'],
  showMore:false,
  category: "floral"
},
{
  id: 3,
  name: "White Black",
  description: "White black floral silk lace dress with sleeves, luxury prom dress, wedding, gift for her, kimono deep v, birthday, bridesmaid robe",
  price: 590,
  image: ['/content/image/floralWhiteBlack/floralWhiteBlack0.png', 
  '/content/image/floralWhiteBlack/floralWhiteBlack1.png', '/content/image/floralWhiteBlack/floralWhiteBlack2.png', 
  '/content/image/floralWhiteBlack/floralWhiteBlack3.png', '/content/image/floralWhiteBlack/floralWhiteBlack4.png',
  '/content/image/floralWhiteBlack/floralWhiteBlack5.png', '/content/image/floralWhiteBlack/floralWhiteBlack6.png',
  '/content/image/floralWhiteBlack/floralWhiteBlack7.png', '/content/image/floralWhiteBlack/floralWhiteBlack8.png'],
  showMore:false,
  category: "floral"
},
{
  id: 4,
  name: "Abstract black",
  description: "Black silk slip dress for women, silk kimono dress, gift for her, birthday, chiffon, wedding party dress, Cocktail dress, bridesmaid robe",
  price: 395,
  image: ['/content/image/abstractBlack/abstractBlack0.png', 
  '/content/image/abstractBlack/abstractBlack1.png', '/content/image/abstractBlack/abstractBlack2.png', 
  '/content/image/abstractBlack/abstractBlack3.png', '/content/image/abstractBlack/abstractBlack4.png',
  '/content/image/abstractBlack/abstractBlack5.png', '/content/image/abstractBlack/abstractBlack6.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 5,
  name: "Rhinestone Pink",
  description: "Prom silk rhinestone dress with sleeves for women, pink silver silk dress, sparkly shiny luxury dress, gift for her,wedding bridesmaid robe",
  price: 590,
  image: ['/content/image/abstractRhinestonePink/abstractRhinestonePink0.png', 
  '/content/image/abstractRhinestonePink/abstractRhinestonePink1.png', '/content/image/abstractRhinestonePink/abstractRhinestonePink2.png', 
  '/content/image/abstractRhinestonePink/abstractRhinestonePink3.png', '/content/image/abstractRhinestonePink/abstractRhinestonePink4.png',
  '/content/image/abstractRhinestonePink/abstractRhinestonePink5.png', '/content/image/abstractRhinestonePink/abstractRhinestonePink6.png',
  '/content/image/abstractRhinestonePink/abstractRhinestonePink7.png', '/content/image/abstractRhinestonePink/abstractRhinestonePink8.png',
  '/content/image/abstractRhinestonePink/abstractRhinestonePink9.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 6,
  name: "Pink Red",
  description: "Prom Black pink red silk dress for women, prom dress, silk kimono, wedding, birthday, floral dress with sleeves,Cocktail bridesmaid robe",
  price: 590,
  image: ['/content/image/floralPinkRed/floralPinkRed0.png', 
  '/content/image/floralPinkRed/floralPinkRed1.png', '/content/image/floralPinkRed/floralPinkRed2.png', 
  '/content/image/floralPinkRed/floralPinkRed3.png', '/content/image/floralPinkRed/floralPinkRed4.png',
  '/content/image/floralPinkRed/floralPinkRed5.png', '/content/image/floralPinkRed/floralPinkRed6.png',
  '/content/image/floralPinkRed/floralPinkRed7.png', '/content/image/floralPinkRed/floralPinkRed8.png',
  '/content/image/floralPinkRed/floralPinkRed9.png'],
  showMore:false,
  category: "floral"
},
{
  id: 7,
  name: "Shiny",
  description: "Prom silk dress with sleeves for women, floral, gift for her, sexy lace dress, luxury silk shiny dress, birthday, wedding bridesmaid robe",
  price: 790,
  image: ['/content/image/abstractShiny/abstractShiny0.png', 
  '/content/image/abstractShiny/abstractShiny1.png', '/content/image/abstractShiny/abstractShiny2.png', 
  '/content/image/abstractShiny/abstractShiny3.png', '/content/image/abstractShiny/abstractShiny4.png',
  '/content/image/abstractShiny/abstractShiny5.png', '/content/image/abstractShiny/abstractShiny6.png',
  '/content/image/abstractShiny/abstractShiny7.png', '/content/image/abstractShiny/abstractShiny8.png',
  '/content/image/abstractShiny/abstractShiny9.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 8,
  name: "Black green",
  description: "Black green silk sparkly dress for women, luxury shiny dress, prom dress with sleeves, gift for her, wedding, Cocktail bridesmaid robe",
  price: 590,
  image: ['/content/image/floralBlackGreen/floralBlackGreen0.png', 
  '/content/image/floralBlackGreen/floralBlackGreen1.png', '/content/image/floralBlackGreen/floralBlackGreen2.png', 
  '/content/image/floralBlackGreen/floralBlackGreen3.png', '/content/image/floralBlackGreen/floralBlackGreen4.png',
  '/content/image/floralBlackGreen/floralBlackGreen5.png', '/content/image/floralBlackGreen/floralBlackGreen6.png',
  '/content/image/floralBlackGreen/floralBlackGreen7.png', '/content/image/floralBlackGreen/floralBlackGreen8.png',
  '/content/image/floralBlackGreen/floralBlackGreen9.png'],
  showMore:false,
  category: "floral"
},
{
  id: 9,
  name: "White red",
  description: "White red silk kimono sexy dress with sleeves, prom dress, gift for her, cocktail silk dress, bridesmaid robe, wedding party",
  price: 590,
  image: ['/content/image/floralWhiteRed/floralWhiteRed0.png', 
  '/content/image/floralWhiteRed/floralWhiteRed1.png', '/content/image/floralWhiteRed/floralWhiteRed2.png', 
  '/content/image/floralWhiteRed/floralWhiteRed3.png', '/content/image/floralWhiteRed/floralWhiteRed4.png',
  '/content/image/floralWhiteRed/floralWhiteRed5.png', '/content/image/floralWhiteRed/floralWhiteRed6.png',
  '/content/image/floralWhiteRed/floralWhiteRed7.png', '/content/image/floralWhiteRed/floralWhiteRed8.png',
  '/content/image/floralWhiteRed/floralWhiteRed9.png'],
  showMore:false,
  category: "floral"
},
{
  id: 10,
  name: "Pink",
  description: "Pink checkered silk dress for women, checkered lace silk kimono dress, gift for her, wedding,silk chiffon,birthday dress,Cocktail silk dress",
  price: 395,
  image: ['/content/image/abstractPink/abstractPink0.png', 
  '/content/image/abstractPink/abstractPink1.png', '/content/image/abstractPink/abstractPink2.png', 
  '/content/image/abstractPink/abstractPink3.png', '/content/image/abstractPink/abstractPink4.png',
  '/content/image/abstractPink/abstractPink5.png', '/content/image/abstractPink/abstractPink6.png',
  '/content/image/abstractPink/abstractPink7.png', '/content/image/abstractPink/abstractPink8.png',
  '/content/image/abstractPink/abstractPink9.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 11,
  name: "Blue",
  description: "Blue white checkered silk dress for women, checkered lace silk kimono dress, gift for her, wedding party dress, Cocktail silk dress,birthday",
  price: 395,
  image: ['/content/image/abstractBlue/abstractBlue0.png', 
  '/content/image/abstractBlue/abstractBlue1.png', '/content/image/abstractBlue/abstractBlue2.png', 
  '/content/image/abstractBlue/abstractBlue3.png', '/content/image/abstractBlue/abstractBlue4.png',
  '/content/image/abstractBlue/abstractBlue5.png', '/content/image/abstractBlue/abstractBlue6.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 12,
  name: "Black chiffon",
  description: "Floral black silk dress for women, prom dress with sleeves, gift for her, sexy dress, wedding, birthday,chiffon, Cocktail bridesmaid robe",
  price: 590,
  image: ['/content/image/floralBlackChiffon/floralBlackChiffon0.png', 
  '/content/image/floralBlackChiffon/floralBlackChiffon1.png', '/content/image/floralBlackChiffon/floralBlackChiffon2.png', 
  '/content/image/floralBlackChiffon/floralBlackChiffon3.png', '/content/image/floralBlackChiffon/floralBlackChiffon4.png'],
  showMore:false,
  category: "floral"
},
{
  id: 13,
  name: "Purple",
  description: "Prom purple floral silk dress for women, kimono dress, gift for her, wedding, Cocktail silk dress with sleeves,gift for her,bridesmaid robe",
  price: 395,
  image: ['/content/image/floralPurple/floralPurple0.png', 
  '/content/image/floralPurple/floralPurple1.png', '/content/image/floralPurple/floralPurple2.png', 
  '/content/image/floralPurple/floralPurple3.png', '/content/image/floralPurple/floralPurple4.png'],
  showMore:false,
  category: "floral"
},
{
  id: 14,
  name: "Purple gold",
  description: "Purple gold silk dress for women, luxury prom dress, kimono, gift for her, wedding, silk dress with sleeves,birthday,deep v, bridesmaid robe",
  price: 590,
  image: ['/content/image/floralPurpleGold/floralPurpleGold0.png', 
  '/content/image/floralPurpleGold/floralPurpleGold1.png', '/content/image/floralPurpleGold/floralPurpleGold2.png', 
  '/content/image/floralPurpleGold/floralPurpleGold3.png', '/content/image/floralPurpleGold/floralPurpleGold4.png',
  '/content/image/floralPurpleGold/floralPurpleGold5.png', '/content/image/floralPurpleGold/floralPurpleGold6.png',
  '/content/image/floralPurpleGold/floralPurpleGold7.png'],
  showMore:false,
  category: "floral"
},
{
  id: 15,
  name: "Purple chiffon",
  description: "Purple floral silk dress for women, kimono dress, gift for her, birthday, prom dress, cocktail party dress with sleeves, bridesmaid robe",
  price: 690,
  image: ['/content/image/floralPurpleChiffon/floralPurpleChiffon0.png', 
  '/content/image/floralPurpleChiffon/floralPurpleChiffon1.png', '/content/image/floralPurpleChiffon/floralPurpleChiffon2.png', 
  '/content/image/floralPurpleChiffon/floralPurpleChiffon3.png', '/content/image/floralPurpleChiffon/floralPurpleChiffon4.png',
  '/content/image/floralPurpleChiffon/floralPurpleChiffon5.png', '/content/image/floralPurpleChiffon/floralPurpleChiffon6.png',
  '/content/image/floralPurpleChiffon/floralPurpleChiffon7.png', '/content/image/floralPurpleChiffon/floralPurpleChiffon8.png',
  '/content/image/floralPurpleChiffon/floralPurpleChiffon9.png'],
  showMore:false,
  category: "floral"
},
{
  id: 16,
  name: "Yellow",
  description: "Yellow red floral silk dress for women, Luxury silk dress with sleeves, gift for her,birthday, Cocktail dress,wedding party dress,prom dress",
  price: 395,
  image: ['/content/image/abstractYellow/abstractYellow0.png', 
  '/content/image/abstractYellow/abstractYellow1.png', '/content/image/abstractYellow/abstractYellow2.png', 
  '/content/image/abstractYellow/abstractYellow3.png', '/content/image/abstractYellow/abstractYellow4.png',
  '/content/image/abstractYellow/abstractYellow5.png', '/content/image/abstractYellow/abstractYellow6.png',
  '/content/image/abstractYellow/abstractYellow7.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 17,
  name: "Brown",
  description: "Brown pink Luxury silk dress for women, prom dress, silk kimono, gift for her, wedding, Cocktail silk dress with sleeves, bridesmaid robe",
  price: 590,
  image: ['/content/image/abstractBrown/abstractBrown0.png', 
  '/content/image/abstractBrown/abstractBrown1.png', '/content/image/abstractBrown/abstractBrown2.png', 
  '/content/image/abstractBrown/abstractBrown3.png', '/content/image/abstractBrown/abstractBrown4.png',
  '/content/image/abstractBrown/abstractBrown5.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 18,
  name: "Orange",
  description: "Floral orange silk dress for women, prom dress, kimono dress, gift for her, silk satin dress, birthday dress, wedding, Cocktail silk dress",
  price: 395,
  image: ['/content/image/floralOrange/floralOrange0.png', 
  '/content/image/floralOrange/floralOrange1.png', '/content/image/floralOrange/floralOrange2.png', 
  '/content/image/floralOrange/floralOrange3.png', '/content/image/floralOrange/floralOrange4.png'],
  showMore:false,
  category: "floral"
},
{
  id: 19,
  name: "Black Ivory",
  description: "Black silk dress for women with sleeves, luxury prom dress, silk kimono dress, gift for her, Cocktail silk dress, wedding, bridesmaid robe",
  price: 395,
  image: ['/content/image/abstractBlackIvory/abstractBlackIvory0.png', 
  '/content/image/abstractBlackIvory/abstractBlackIvory1.png', '/content/image/abstractBlackIvory/abstractBlackIvory2.png', 
  '/content/image/abstractBlackIvory/abstractBlackIvory3.png'],
  showMore:false,
  category: "abstract"
},
{
  id: 20,
  name: "Mint",
  description: "Prom Mint silk slip dress for women with sleeves, natural silk kimono dress, gift for her,Cocktail dress, wedding party, bridesmaid robe",
  price: 590,
  image: ['/content/image/abstractMint/abstractMint0.png', 
  '/content/image/abstractMint/abstractMint1.png', '/content/image/abstractMint/abstractMint2.png', 
  '/content/image/abstractMint/abstractMint3.png', '/content/image/abstractMint/abstractMint4.png',
  '/content/image/abstractMint/abstractMint5.png', '/content/image/abstractMint/abstractMint6.png',
  '/content/image/abstractMint/abstractMint7.png', '/content/image/abstractMint/abstractMint8.png',
  '/content/image/abstractMint/abstractMint9.png'],
  showMore:false,
  category: "abstract"
},

]

export default data;