export const data = [
{
  id: 1,
  name: "Floral black",
  description: "Floral black orange silk dress for women, prom dress, silk kimono, gift for her, wedding party, birthday, cocktail silk dress with sleeves",
  price: 590,
  image: ['https://drive.google.com/uc?id=1eluOTfMTNmmlSgYIAr0BsY2NU_M0Lq5u',
  'https://drive.google.com/uc?id=1oIL0-wQHYpiy7larGAGr3-Iv5ecZrur4',
  'https://drive.google.com/uc?id=1ub4smteWzha1FT7Oan-CVHBgrGzYJ0Dy',
  'https://drive.google.com/uc?id=1hN-yBvFThi06OgGF086V0J76hN2ZdrYU',
  'https://drive.google.com/uc?id=1ciuRM-ktiYTawzAGIPeL3t2ode89EtMd',
  'https://drive.google.com/uc?id=1z91fGnJdigxik7X2B8xjCJHtkToX17JD',
  'https://drive.google.com/uc?id=1FzwEA0T0YsuNWnl5MnJzUHY289fkeJol',
  'https://drive.google.com/uc?id=1c12fgCRSlu8OuOxgZZpX6HAzJPb6VtgE',
  'https://drive.google.com/uc?id=1TgQr7MbU5t3S8y8Twj3RJ4k5V7Efa4m1',
  'https://drive.google.com/uc?id=13QCba1Tkzn4Q8pt8Cefd2ay-uP57dRzV',
  'https://drive.google.com/uc?id=1qh6jxUXbafwHO3xtwULmR27woIDn0mjS'],
  showMore:false,
  category: "floral"
},
{
  id: 2,
  name: "Sakura",
  description: "Prom Green pink silk dress with sleeves for women, Sakura kimono dress,gift for her,teal dress, wedding,cocktail bridesmaid robe birthday",
  price: 690,
  image: ['https://drive.google.com/uc?id=1wZUeXqMlrjTU6U3CR5rEpxi9lulDxF9U',
  'https://drive.google.com/uc?id=1lIMWkCNeH84rERFOocKM_q8FwecZBpVV',
  'https://drive.google.com/uc?id=10XkCkCjHifyxsyZCj_kBOwcosiX855iu',
  'https://drive.google.com/uc?id=1-6wM152Cvu5y0YGnz7tS_AGpqJEIZ3L2',
  'https://drive.google.com/uc?id=1mWXuS4_REigq0sZ-C3xpJ_D9vHD4Cf1F',
  'https://drive.google.com/uc?id=1gvqWg6iW5vJ1ePkqV7nwYwndVwVmlhWA',
  'https://drive.google.com/uc?id=1nSEEHe7qvoKPxQ9G80GIsd7JIWDsq3G7'],
  showMore:false,
  category: "floral"
},
{
  id: 3,
  name: "White Black",
  description: "White black floral silk lace dress with sleeves, luxury prom dress, wedding, gift for her, kimono deep v, birthday, bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1kYLw1tFsn76ieG3V32csf3470vbOaHIX',
  'https://drive.google.com/uc?id=19Fl7AXgOqywSqTxNm4iVWMb7yz5wpg3W',
  'https://drive.google.com/uc?id=1btLjLOw9YO3yJ4-gGElj2eMfPRv_UYT3',
  'https://drive.google.com/uc?id=1D-Ipn2O40gmt2tDsDYa73vXGYZNa1Y5y',
  'https://drive.google.com/uc?id=1vDdjIdDxrI5RfR9Ue7JC1o8QerMh7dGD',
  'https://drive.google.com/uc?id=1N81pLFCDBysx8grGfdDXKKBatc3hp8gp',
  'https://drive.google.com/uc?id=1y70lc6nucKLqaTOobQmqvBa819to9rgQ',
  'https://drive.google.com/uc?id=1eMeGtr8chbesL2pp2Dvh0d3J4a74NRtj',
  'https://drive.google.com/uc?id=1mqTP9T9-q0m1fmrRsqPpbi3yOLUnldIi',
  'https://drive.google.com/uc?id=1OH4UXLYXRtYhT0ib2zAPmCevqpwmenLm'],
  showMore:false,
  category: "floral"
},
{
  id: 4,
  name: "Abstract black",
  description: "Black silk slip dress for women, silk kimono dress, gift for her, birthday, chiffon, wedding party dress, Cocktail dress, bridesmaid robe",
  price: 395,
  image: ['https://drive.google.com/uc?id=119YdZIsax2ioK-LDrB1BDZNpgjBPmLIC',
  'https://drive.google.com/uc?id=16dW1SF3kMeeQEQAiPO0QJg-PD11GtlnI',
  'https://drive.google.com/uc?id=1S5aeuUHVpcmsSzWhbwNDtuCkVoZYH-c9',
  'https://drive.google.com/uc?id=1vwUULzMmlPhPP_oF2__GD-QkkuJdhtCh',
  'https://drive.google.com/uc?id=1r9nLVLO3dBqmwIvx6nA05yumrLD1eIcy',
  'https://drive.google.com/uc?id=1TlV3WmbYEAmeSbeUEctgxtpG6Jd0hRZh',
  'https://drive.google.com/uc?id=1x89E2K9KxW_2AHJ3Dyp59g9Ga6u7gCu7',
  'https://drive.google.com/uc?id=1jqmzIRGZ_iiHS2jVeWwdJTpIXc7jSJ_X'],
  showMore:false,
  category: "abstract"
},
{
  id: 5,
  name: "Rhinestone Pink",
  description: "Prom silk rhinestone dress with sleeves for women, pink silver silk dress, sparkly shiny luxury dress, gift for her,wedding bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=11l7noNCGYA5n0mtGJXN6QQoKcuk3R_9n',
  'https://drive.google.com/uc?id=1PtgQ3HniF7WICZy7dFVZnyV4Zs4YE2Rj',
  'https://drive.google.com/uc?id=1ttLONrr83sJR71KCCPuowMp6qHw8lED9',
  'https://drive.google.com/uc?id=1ZqtbMyAaw0_FaT_zUC_s778b2bJ0b5-b',
  'https://drive.google.com/uc?id=1yz_QblrjCrcurMis5Tt6tWN-QY33SnbJ',
  'https://drive.google.com/uc?id=1VKFVowFqOZyXDom4EVqsPPRyE6xpXXC0',
  'https://drive.google.com/uc?id=1JrIt-4-3-12S69y9uWg9lLktqWYBexEY',
  'https://drive.google.com/uc?id=1hZ_Npv_r5BFMhD_WfcBvL-hnv2JoA4SS',
  'https://drive.google.com/uc?id=1tcf-BayFxI1xcgglrw0wabYlRrnbAieN',
  'https://drive.google.com/uc?id=1Xfzh220Kw3Bi8MZna2hgezVKw6WaJGPP',
  'https://drive.google.com/uc?id=1j4CftpGThMszU5fahIZmO8xRYIK-IsZ0'],
  showMore:false,
  category: "abstract"
},
{
  id: 6,
  name: "Pink Red",
  description: "Prom Black pink red silk dress for women, prom dress, silk kimono, wedding, birthday, floral dress with sleeves,Cocktail bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1uJmpG2Szb2rCLubThCEkTnEo-Uwr0bis',
  'https://drive.google.com/uc?id=1-g8fQasXhsNXk0ajYQUUQ2lodb3MVN2a',
  'https://drive.google.com/uc?id=1vjq_I_pd8-n7hUHjiPGGAR3ppVdTWYcG',
  'https://drive.google.com/uc?id=1SVofrIb8Wrn_rNsGsO88PNdtGQ48cvUf',
  'https://drive.google.com/uc?id=12HxoHQfcWKFANTWhBVuLh699vJ-Ajj0n',
  'https://drive.google.com/uc?id=1iyN8XtjS1Kd1uJAi9heutbu0nkrOIfKE',
  'https://drive.google.com/uc?id=1pUgaCuKtbZfULDw2f1eH6ljzZheX4HNJ',
  'https://drive.google.com/uc?id=1J78Jro_v8rf3k3V_qdGllNaFBCAAu-nl',
  'https://drive.google.com/uc?id=1M4hUCkxoVALkS8Pg9Om5gURRn-TH1TTe',
  'https://drive.google.com/uc?id=1883wON-7dv965yBO4e1riLyzLqozT3Jt',
  'https://drive.google.com/uc?id=1r9d5V3X8sQAd9I0BdSccGPBJ1BJDokcS'],
  showMore:false,
  category: "floral"
},
{
  id: 7,
  name: "Shiny",
  description: "Prom silk dress with sleeves for women, floral, gift for her, sexy lace dress, luxury silk shiny dress, birthday, wedding bridesmaid robe",
  price: 790,
  image: ['https://drive.google.com/uc?id=1tteIZq8Lj2SoLgRrn78wQCCx6hzEvuLn',
  'https://drive.google.com/uc?id=1KMezvz9ZWoVDgeMaobnRa0Dius-XAysj',
  'https://drive.google.com/uc?id=1fNgfpXnqZg4wNvBRU2-r9PXH0uYwzWAF',
  'https://drive.google.com/uc?id=1zerpAKISBXAhscW2xyetlsLWbGqN8Swa',
  'https://drive.google.com/uc?id=1JqxbhgazNnxWl8q2uDsiyoLVv2DBCQo0',
  'https://drive.google.com/uc?id=1Lf_FLKoKQs1-2372ukxW73YYbO_QdqT_',
  'https://drive.google.com/uc?id=1f_0rcNtfiMaMak4LBSQN1QLJfLub99Dt',
  'https://drive.google.com/uc?id=1_wvf4t_JZNB3qO9-l3LJCA4ZDdc0nG_9',
  'https://drive.google.com/uc?id=1GHoHTlS-fZWK1ZI0igK8HMHb5Q6Mg9Mk',
  'https://drive.google.com/uc?id=1U7cBX2z95xwZauwwTMDi9tE2ISLq0omP',
  'https://drive.google.com/uc?id=1HEcpLDYcOJ4m3OmkcWuFnaoCoxQRTzog'],
  showMore:false,
  category: "abstract"
},
{
  id: 8,
  name: "Black green",
  description: "Black green silk sparkly dress for women, luxury shiny dress, prom dress with sleeves, gift for her, wedding, Cocktail bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1v8syXqMruo4HaleMIh5GtoGitAjt1FDg',
  'https://drive.google.com/uc?id=1AxWrjHdHdKs3xTNu0drH6kpN5HYyA-kg',
  'https://drive.google.com/uc?id=1JD4i9iY0uhupVg65iFvuKyN1UJQsF0z_',
  'https://drive.google.com/uc?id=14gZhsEeHpTcbKAKdPqwaLHPyqw3PI_2E',
  'https://drive.google.com/uc?id=1qWa9pxb-D4jlhEF1hwhF_QwNL4A1q1WK',
  'https://drive.google.com/uc?id=1hFMauzaNMUGCGpclEzr4XLujYzyCpzS2',
  'https://drive.google.com/uc?id=1tC0DixN0NbmM7J-ZNatJrQBYdfPo0YEn',
  'https://drive.google.com/uc?id=1W1EHQ7IfLa5NrWg8fw4cedUosbqGUbXF',
  'https://drive.google.com/uc?id=1X95QY-TH_N_Vw66XEcpW3ziJpvvSoPc-',
  'https://drive.google.com/uc?id=1c-3TlKt_bU7iaKKDMi3jQ3u1YDfrsWR6',
  'https://drive.google.com/uc?id=1q6kTx96cEglxsCxUto1iDybeEcino6Qs'],
  showMore:false,
  category: "floral"
},
{
  id: 9,
  name: "White red",
  description: "White red silk kimono sexy dress with sleeves, prom dress, gift for her, cocktail silk dress, bridesmaid robe, wedding party",
  price: 590,
  image: ['https://drive.google.com/uc?id=1v3ybQEAr4kegCIemES-ldnoH738nbZkw',
  'https://drive.google.com/uc?id=14HqSKx7oYe0lvgcN244nWQuHiw2i_W2a',
  'https://drive.google.com/uc?id=1Rzf0N2KXQhUNmHj1XKQDYCzH9m00jTr6',
  'https://drive.google.com/uc?id=1GIQZM5X_hJgzFVfrEe2Q7Nza8fjgeXrR',
  'https://drive.google.com/uc?id=116Wmn10OZ2wZfl7Tj47TwAWfHp1kuxrE',
  'https://drive.google.com/uc?id=1xqz9nX1eeXgBpupcG7RiCceTrk6EMwaN',
  'https://drive.google.com/uc?id=1RPlRVsMftO18ZUHstamer2vLTqEQDpWZ',
  'https://drive.google.com/uc?id=1E9N3dEDozJDZWERB5W0VaKvjcLe-cLrT',
  'https://drive.google.com/uc?id=1MzGoyCzDEIBS3zE7yFXrPe8MclAxRitd',
  'https://drive.google.com/uc?id=1lvDD50PLhIAI4OeqmnxUCZfQWSmxAvcc',
  'https://drive.google.com/uc?id=1bs7nUVFEcQ4Q64i6pxJ7rUIRr2EfmR67'],
  showMore:false,
  category: "floral"
},
{
  id: 10,
  name: "Pink",
  description: "Pink checkered silk dress for women, checkered lace silk kimono dress, gift for her, wedding,silk chiffon,birthday dress,Cocktail silk dress",
  price: 395,
  image: ['https://drive.google.com/uc?id=173orRmiB-hOd-9g2_sgHhqmKs03op2Uu',
  'https://drive.google.com/uc?id=1-JtlKWnqKQacrq3l3R4ik3h-cT0oiGk6',
  'https://drive.google.com/uc?id=1r8wYMjMiB879qA5hit58uDUHZqHqAtEl',
  'https://drive.google.com/uc?id=1Xzz6vQPzIOoioW1pRdHSStCFof1scHLk',
  'https://drive.google.com/uc?id=1IybYphUScojNv1uUVnz97eZRqKfSFea0',
  'https://drive.google.com/uc?id=1fSh9gOi1lboiIxSJI95BcA9xqhbu-4ub',
  'https://drive.google.com/uc?id=1szI4hDx_pYCug5CKP33dthpwxdNG5LR8',
  'https://drive.google.com/uc?id=1t1laH9ZSopAHSMWFGpPPsjE7Zj4t6i_t',
  'https://drive.google.com/uc?id=1rq5sKqdauGwI-IbwUndedQ-Ldm9XlDZI',
  'https://drive.google.com/uc?id=1iWr9gZ7wz2aT2tCPsSiUlPQNVFhNodzl'],
  showMore:false,
  category: "abstract"
},
{
  id: 11,
  name: "Blue",
  description: "Blue white checkered silk dress for women, checkered lace silk kimono dress, gift for her, wedding party dress, Cocktail silk dress,birthday",
  price: 395,
  image: ['https://drive.google.com/uc?id=181in5uBseg5f1vXc062wcbeISXa0Vdpu',
  'https://drive.google.com/uc?id=1DZQeg0arSLPoZdxI4rpwhDZ5lm3McTJu',
  'https://drive.google.com/uc?id=1GDxsDSNujoBYSFwi53co8hBsU3K4sYz_',
  'https://drive.google.com/uc?id=1Qe-Kndm__Lmi9vHeORLh4XQpWy_6zBR6',
  'https://drive.google.com/uc?id=1AGmtLA3StLLAYmwoyvqoQEGdqW5JztqU',
  'https://drive.google.com/uc?id=1PRU3QB_Fy6Dxq1OIbRUKOEMGrrIu5q-a',
  'https://drive.google.com/uc?id=1Ku48r31GUmg8qUKn9eq6H3w5LTFclNmR',
  'https://drive.google.com/uc?id=1J11krqjukiIxIP4SUyvL-vatv4SzxSw-'],
  showMore:false,
  category: "abstract"
},
{
  id: 12,
  name: "Black chiffon",
  description: "Floral black silk dress for women, prom dress with sleeves, gift for her, sexy dress, wedding, birthday,chiffon, Cocktail bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1-TIfVPxAHsU1py9qYWW4XOzmDrKo8TS4',
  'https://drive.google.com/uc?id=1cYV3MTfWS-HKZsaKYGBN8WsGVIocdU8P',
  'https://drive.google.com/uc?id=1II3Dx8Atm9RIGZup31YD_bV5H2SDLjNg',
  'https://drive.google.com/uc?id=1p5lw0h3jtdjK7GRPUwipZ7a02W2cHBGI',
  'https://drive.google.com/uc?id=1627A8EYa7vQ4JTV6l7FbmwSapwYRqrxI'],
  showMore:false,
  category: "floral"
},
{
  id: 13,
  name: "Purple",
  description: "Prom purple floral silk dress for women, kimono dress, gift for her, wedding, Cocktail silk dress with sleeves,gift for her,bridesmaid robe",
  price: 395,
  image: ['https://drive.google.com/uc?id=1G76mYJFmAUGPJiw3nKdvaqpszJTSXvpi',
  'https://drive.google.com/uc?id=1413braXpkwp_CW1QNWk20GF2R6EI-4h_',
  'https://drive.google.com/uc?id=1Xqqm0UKlbhWg3Spx-vqBsnI3WdkWLQ9M',
  'https://drive.google.com/uc?id=1jqkErhSGjiXGxKTyLoAVQEQR2ZW2WbX9',
  'https://drive.google.com/uc?id=1YnjIJfeJF3zfhzeHnFbMemBXzZ2UFU94',
  'https://drive.google.com/uc?id=1OO9CGl85XoCunH4qqlD4a0rs7BsSENo1'],
  showMore:false,
  category: "floral"
},
{
  id: 14,
  name: "Purple gold",
  description: "Purple gold silk dress for women, luxury prom dress, kimono, gift for her, wedding, silk dress with sleeves,birthday,deep v, bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1BGq6W-7Fc3NF4rwuiKz48Z5Y2gkkWmHD',
  'https://drive.google.com/uc?id=1jo9k-WiFKqksBA5ZzRPEnvKOiI7YyT5X',
  'https://drive.google.com/uc?id=1m84jmw6w7bnsSh9XmR_hcg_II3w7DD3p',
  'https://drive.google.com/uc?id=10ei8IJczXA8zACr0jv5wm1e0L_7YQn22',
  'https://drive.google.com/uc?id=1zw2iva4jqTgdmNXCvZoOjmRMw4n3t5gq',
  'https://drive.google.com/uc?id=13rfj8kaourx_w5AgIua22vhK0z1HqKTb',
  'https://drive.google.com/uc?id=1rl-zyZ1pbzvVj6VX7_I8w65sCm3cw9jb',
  'https://drive.google.com/uc?id=180M-o0-Ky0TBULpQV4ligdN9EzwLYNC5',
  'https://drive.google.com/uc?id=1iJKhCSb6eRNgKF9rpNNJ67W-gC5uhtJx'],
  showMore:false,
  category: "floral"
},
{
  id: 15,
  name: "Purple chiffon",
  description: "Purple floral silk dress for women, kimono dress, gift for her, birthday, prom dress, cocktail party dress with sleeves, bridesmaid robe",
  price: 690,
  image: ['https://drive.google.com/uc?id=1e_eLkY82xHeN-iXBpbMvJqk6jtotuaLQ',
  'https://drive.google.com/uc?id=1i8G5IyykvWXu91KVHI3icmK4mLv4LNKb',
  'https://drive.google.com/uc?id=1BUiutoaUwLtaQRkFqtbt_8xMDB9evbRZ',
  'https://drive.google.com/uc?id=1AsLVyfR05A0oSlMRNHFYORGzvTcXN38K',
  'https://drive.google.com/uc?id=1Q5VlhX8dUfDNZG8vZtVQ7dEjgHGggRHF',
  'https://drive.google.com/uc?id=18ofkiqEorm8SBR70UNPxSzrdt8-ubY-l',
  'https://drive.google.com/uc?id=1Avt3UuYip89Rtu8wjhwJ-1LG43iRt-t8',
  'https://drive.google.com/uc?id=1TFJf_WZHzjEafnesLK1HPDR8K57E88XF',
  'https://drive.google.com/uc?id=12PXeWWLt_0-GP4aal0_8g2WFYKFLnXSe',
  'https://drive.google.com/uc?id=1pi3uwdwtkIJSBqI4SBfTWo8cg2XWEzEu'],
  showMore:false,
  category: "floral"
},
{
  id: 16,
  name: "Yellow",
  description: "Yellow red floral silk dress for women, Luxury silk dress with sleeves, gift for her,birthday, Cocktail dress,wedding party dress,prom dress",
  price: 395,
  image: ['https://drive.google.com/uc?id=1kCCQKOokSn5w7K2o1q1L7d9xyWySrQXM',
  'https://drive.google.com/uc?id=1AD63jUF7pFOJejR0iEkZQ-9O81ZGepXm',
  'https://drive.google.com/uc?id=11Qs28dEySRHP-MFp0uTcuUwc9URHvVEj',
  'https://drive.google.com/uc?id=1PoVECq5ErIrefe5k3_2Bko4bss-yuOZB',
  'https://drive.google.com/uc?id=18G63CslhmyrESq9vusUMzOyM6oo1LsN-',
  'https://drive.google.com/uc?id=1dm8YyYBk2bZZNedcxgtBNG3BkQna6T03',
  'https://drive.google.com/uc?id=1tFU26exkjFr_Ik4tCfPIg_1mrrIscyG8',
  'https://drive.google.com/uc?id=135CpZh0Tt47xijs9boGVN_EtHLXO4Ntt',
  'https://drive.google.com/uc?id=1cXFJcb-7tDztob9TZCgedAuK62XrU-T5'],
  showMore:false,
  category: "abstract"
},
{
  id: 17,
  name: "Brown",
  description: "Brown pink Luxury silk dress for women, prom dress, silk kimono, gift for her, wedding, Cocktail silk dress with sleeves, bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1KwsaFsoXNySkaQcnilyUIibLEQeOvkol',
  'https://drive.google.com/uc?id=10nLBAeGVRm9CFE5XQyheVZHT26AEoLsb',
  'https://drive.google.com/uc?id=1kf-Igsu5RZZvnsLrlVqhkdTp0dW-O_g6',
  'https://drive.google.com/uc?id=1bga6W0PwRSWUY0SluT02Q4OcYMd1Yq-p',
  'https://drive.google.com/uc?id=171wB-Sxj1hKeQ87peQ4v5_oItj6-dZ68',
  'https://drive.google.com/uc?id=1_I5ADiqEAwxeD4cpXp818Nb4fwHEHDBu'],
  showMore:false,
  category: "abstract"
},
{
  id: 18,
  name: "Orange",
  description: "Floral orange silk dress for women, prom dress, kimono dress, gift for her, silk satin dress, birthday dress, wedding, Cocktail silk dress",
  price: 395,
  image: ['https://drive.google.com/uc?id=15EDKYswaQUoi8-LIJTDKRGN6t1M_92Iw',
  'https://drive.google.com/uc?id=1oRkckdzieLdLfKVmuiLDbIHeJzhgc9zF',
  'https://drive.google.com/uc?id=15uj_V_OZTAVTBs4JD_D4q6r_dlPBFWHj',
  'https://drive.google.com/uc?id=1Gl1nbuNcM0yzrZ_m4Wy5xS4mT6g86HtV',
  'https://drive.google.com/uc?id=1SFV93KAEt-mFIDtH1NLvHwfloHUtos1b'],
  showMore:false,
  category: "floral"
},
{
  id: 19,
  name: "Black Ivory",
  description: "Black silk dress for women with sleeves, luxury prom dress, silk kimono dress, gift for her, Cocktail silk dress, wedding, bridesmaid robe",
  price: 395,
  image: ['https://drive.google.com/uc?id=1ht6rPCSWx2Q2WMJXaKqUkqkc5k8DaLtz',
  'https://drive.google.com/uc?id=1wsPCeLpUpSAeBbB4SZCSWAYFJ82Fm8JW',
  'https://drive.google.com/uc?id=1SFTx-8mwLh3IJzWFCWHnOlSssKLzmJPj',
  'https://drive.google.com/uc?id=1bawFVRQAnyhOdynMGO6KuX-KxRxJ_C5D'],
  showMore:false,
  category: "abstract"
},
{
  id: 20,
  name: "Mint",
  description: "Prom Mint silk slip dress for women with sleeves, natural silk kimono dress, gift for her,Cocktail dress, wedding party, bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=1Ib2JGd8ImQCgr7xmYjz9YydUgLwLemWE',
  'https://drive.google.com/uc?id=1Jopd5BWOJLgRjMspoZmdORn_h4ipQdO-',
  'https://drive.google.com/uc?id=15F2abuyBKJYmSEqsPuf8_yRAHwmxG-Wk',
  'https://drive.google.com/uc?id=1UYENOaRVVbEBjHW-701WVtAaDmXQzdEs',
  'https://drive.google.com/uc?id=1dULF1jsZJUpaDglUikjeGkAnx_ch6UwI',
  'https://drive.google.com/uc?id=18SuBA18WoJ-k0TPTlTi9Jo6GGe1lV4vS',
  'https://drive.google.com/uc?id=1dE1AP6OvFxiuhplmifmHRQAK1WxVGg7g',
  'https://drive.google.com/uc?id=1rtA-mhCJWdgvd9up46iygcxHj5AzwmNR',
  'https://drive.google.com/uc?id=1lhyYNzYsao1Sk-lWYlzH8jayKCSkG5vG',
  'https://drive.google.com/uc?id=1NwZFBMj0S3UfVef8pprfBpCzYU1N4U2u',
  'https://drive.google.com/uc?id=1zh5C1WYFUxumRNU4FrGj0XyxZg9PGegq'],
  showMore:false,
  category: "abstract"
},
{
  id: 21,
  name: "Beige Red",
  description: "Beige red silk dress for women, prom silk kimono dress sleeves,gift for her,sexy luxury silk dress,Cocktail birthday,wedding bridesmaid robe",
  price: 590,
  image: ['https://drive.google.com/uc?id=14E923tc2j0TOHgdZN_LBnd4WuM822p1Q',
  'https://drive.google.com/uc?id=1qrSafOcsl3sa9ymKUAfzueaeuu4hndzK'],
  showMore:false,
  category: "abstract"
}
]

export default data;